name: CI Test

on:
  push:
    branches: [ main, v3-staging ]
    paths-ignore:
      - 'ceremony/**'
  pull_request:
    branches: [ main, v3-staging ]
    paths-ignore:
      - 'ceremony/**'

env:
  GO_VERSION: 1.17.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29 # v3
        timeout-minutes: 5
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.39

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: go test -v ./...
      - name: Ensure no files were modified as a result of the build
        run: git update-index --refresh && git diff-index --quiet HEAD -- || git diff --exit-code
      
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install deps
        run: |
          sudo apt-get install libpcsclite-dev
      - name: build verification
        run: go build -o verify ./cmd/verify/
      - name: build TUF script
        run: go build -o tuf -tags=pivkey ./cmd/tuf